### ISSUE TITLE
v1.3.0 checklist

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/auditor#153]
- [x] `rhub::check_for_cran()`
- [x] `rhub::check_with_rdevel()`
- [x] `usethis::use_cran_comments()`
- [x] `devtools::submit_cran()`
- [x] accept the mail
- [x] tag release on GitHub

**Comment by agosiewska** [comment]
Done.
Thanks!
